name: publish

on:
  workflow_dispatch

jobs:
  publish:
    runs-on: macos-12

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - uses: leleliu008/github-actions-vagrant@main
        with:
          mem: 4096
          box: generic/dragonflybsd6
          run: |
            PKG_NAMES='bash bison bzip2 coreutils cppcheck curlie curl darkhttpd diffutils dos2unix ed file findutils flex fzf gawk gettext gettext-tools gm4 gmake gnupg git gogs gotty gperf grep gsed gtar gzip hugo jq libarchive lzip lz4 mediainfo mpg123 nasm ninja openssl patchelf patch pkgconf pkg-config putty pigz qpdf re2c rtmpdump sqlite3 svn-lite swig tcpdump tig tmux tree uctags unrar unzip uppm xxd xz yasm yq zopfli zip p7zip zstd zsync base16 base64 sysinfo easyutils'

            export HOME='/home/vagrant'

            run cd "$HOME"

            run curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
            run chmod a+x ppkg

            run ./ppkg setup --use-system-package-manager
            run ./ppkg update
            run ./ppkg install "$PKG_NAMES" --link-type=static-full

            for PKG_NAME in $(./ppkg ls-installed)
            do
              run ./ppkg pack "$PKG_NAME"
            done

            date +%Y.%m.%d > ts.txt

            TAGNAME="$(cat ts.txt)"

            install -d formula

            for PACKAGE_SPEC in $(./ppkg ls-installed)
            do
              PACKAGE_SUMMARY="$(./ppkg receipt "$PACKAGE_SPEC" summary)"
              PACKAGE_VERSION="$(./ppkg receipt "$PACKAGE_SPEC" version)"
              PACKAGE_WEB_URL="$(./ppkg receipt "$PACKAGE_SPEC" web-url)"

              PACKAGE_NAME="${PACKAGE_SPEC##*/}"

              TARGET_PLATFORM="${PACKAGE_SPEC%/*}"

              PACKAGE_BIN_FILENAME="$PACKAGE_NAME-$PACKAGE_VERSION-$TARGET_PLATFORM.tar.xz"

              PACKAGE_BIN_SHA=$(gsha256sum "$PACKAGE_BIN_FILENAME" | cut -d ' ' -f1)

              PACKAGE_BIN_URL="https://github.com/leleliu008/uppm-package-repository-$TARGET_PLATFORM/releases/download/$TAGNAME/$PACKAGE_BIN_FILENAME"

              printf '%s\n' "\
            summary: $PACKAGE_SUMMARY
            webpage: $PACKAGE_WEB_URL
            version: $PACKAGE_VERSION
            bin-url: $PACKAGE_BIN_URL
            bin-sha: $PACKAGE_BIN_SHA" > "formula/$PACKAGE_NAME.yml"
            done

      - run: install -d formula

      - run: scp -i $VAGRANT_CWD/.vagrant/machines/default/virtualbox/private_key -o StrictHostKeyChecking=no -r -P 2222 vagrant@127.0.0.1:/home/vagrant/formula/*.yml formula

      - run: scp -i $VAGRANT_CWD/.vagrant/machines/default/virtualbox/private_key -o StrictHostKeyChecking=no -r -P 2222 vagrant@127.0.0.1:/home/vagrant/*.tar.xz .
      - run: scp -i $VAGRANT_CWD/.vagrant/machines/default/virtualbox/private_key -o StrictHostKeyChecking=no -r -P 2222 vagrant@127.0.0.1:/home/vagrant/*.txt .

      - run: ls

      - run: |
          TAGNAME="$(cat ts.txt)"
          UPPM_FORMULA_DIRNAME="uppm-formula-repository-dragonflybsd-6.4-x86_64-$TAGNAME"
          ln -s formula "$UPPM_FORMULA_DIRNAME"
          tar cvJf "$UPPM_FORMULA_DIRNAME.tar.xz" "$UPPM_FORMULA_DIRNAMEDIR"

      - run: sha256sum *.tar.xz > sha256sums.txt

      - run: |
          cat > notes.md <<EOF
          these packages are created by [ppkg](https://github.com/leleliu008/ppkg).

          these packages are statically-linked.

          these packages are relocatable which means that you can install them to anywhere.

          ## Environment Variables

          **following environment variables should be set for \`git\` package**

          \`\`\`bash
          export GIT_EXEC_PATH="\$GIT_INSTALL_DIR/libexec/git-core"
          export GIT_TEMPLATE_DIR="\$GIT_INSTALL_DIR/share/git-core/templates"
          \`\`\`

          **following environment variables should be set for \`file\` package**

          \`\`\`bash
          export MAGIC="\$FILE_INSTALL_DIR/share/misc/magic.mgc"
          \`\`\`

          ## sha256sum

          \`\`\`
          $(cat sha256sums.txt)
          \`\`\`
          EOF

          TAGNAME="$(cat ts.txt)"

          gh release create "$TAGNAME" *.tar.xz sha256sums.txt --title "$TAGNAME" --notes-file notes.md

          git add formula
          git commit -m "publish new release $TAGNAME"
          git push origin master
